# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en
  # weight: 1

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh
  contentDir: content/zh
  title: 吴诗航的主页
  params:
    description: 吴诗航的主页-中文版本
  menu:
    main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 帖子
        url: '#posts'
        weight: 20
      - name: 项目
        url: '#projects'
        weight: 30
      - name: 会谈
        url: '#talks'
        weight: 40
      - name: 出版物
        url: '#featured'
        weight: 50
      - name: 联系
        url: '#contact'
        weight: 60